services:
  - type: web
    name: qrs-attendance-api
    env: docker
    repo: https://github.com/Ova-Klik/qrs2
    branch: master
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRY_MS
        value: "86400000"
      - key: ALLOWED_ORIGINS
        value: https://qrsattendance.netlify.app
      - key: SEED_DATA
        value: "true"
      - key: QR_WINDOW_START
        value: "07:00"
      - key: QR_WINDOW_END
        value: "12:00"
      - key: LATE_THRESHOLD
        value: "08:31"
      - key: BREVO_SMTP_HOST
        value: smtp-relay.brevo.com
      - key: BREVO_SMTP_PORT
        value: "587"
      - key: BREVO_SMTP_USERNAME
        sync: false
      - key: BREVO_SMTP_PASSWORD
        sync: false
      - key: BREVO_FROM_EMAIL
        sync: false
      - key: BREVO_FROM_NAME
        value: QRAttendance

databases:
  - name: qrs-mongo
    databaseName: qrs_db
    plan: free
