services:
  - type: web
    name: qrs-attendance-api
    env: docker
    repo: https://github.com/Ova-Klik/qrs2
    branch: master
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        value: mongodb+srv://olaomovictor1_db_user:MongoDbPassword@qrs2.jns1ejm.mongodb.net/qrs_db?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: 74fbcbe8c50925d6e570c3d802d4c318687c97b527a0eeddf440e93469f08423716549a035d4d99b654c86a32cfbfeddb5b9cb6d17ea51cc0cffc4958e35cb75
      - key: JWT_EXPIRY_MS
        value: "86400000"
      - key: ALLOWED_ORIGINS
        value: https://qrsattendance.netlify.app
      - key: SEED_DATA
        value: "true"
      - key: QR_WINDOW_START
        value: "07:00"
      - key: QR_WINDOW_END
        value: "12:00"
      - key: LATE_THRESHOLD
        value: "08:31"

databases:
  - name: qrs-mongo
    databaseName: qrs_db
    plan: free
